# Sun-$Revision: 30.6 $

# Copyright 1994-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../..
FILES        = Makefile
SELF_MODULES = parseKit \
	       parseKit1 \
               parseKitCharSets \
	       parseKitCharSets2 \
	       parseKitCharSets3 \
               parseKitErr \
	       parseKitErr1 \
	       parseKitInput \
               parseKitMinis \
               parseKitNodes \
	       parseKitSamples \
	       parseKitTester \
	       parseKitTokens \
               parseKitUI \
               parseNode \

include        ${ROOT}/templates/sources.make
