/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */

MarkValueHeaderField* memoryObject_markField = new MarkValueHeaderField(NULL, NULL);
SmiValueHeaderField* memoryObject_oidField = new SmiValueHeaderField(NULL, memoryObject_markField);
OopValueHeaderField* memoryObject_mapField = new OopValueHeaderField(MarkLayout().compactMapIndexField(), memoryObject_oidField);
SmiValueHeaderField* objVector_indexableOriginField = new SmiValueHeaderField(MarkLayout().objVectorIndexableOriginField(), memoryObject_mapField);
SmiValueHeaderField* objVector_indexableSizeField = new SmiValueHeaderField(MarkLayout().objVectorIndexableSizeField(), objVector_indexableOriginField);
OopValueHeaderField* byteVector_bytesPartRefField = new OopValueHeaderField(NULL, memoryObject_mapField);
OopValueHeaderField* block_homeFramePointerField = new OopValueHeaderField(NULL, memoryObject_mapField);

/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */
