/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */

ObjectLayout* SlotsMapLayout::myLayout() {return new MemoryObjectLayout();}
ObjectLayout* BlockMapLayout::myLayout() {return new BlockLayout();}
ObjectLayout* ObjVectorMapLayout::myLayout() {return new ObjVectorLayout();}
ObjectLayout* ByteVectorMapLayout::myLayout() {return new ByteVectorLayout();}
ObjectLayout* ImmediateMapLayout::myLayout() {return new ImmediateLayout();}
ObjectLayout* SmiMapLayout::myLayout() {return new SmiLayout();}
ObjectLayout* FloatMapLayout::myLayout() {return new FloatLayout();}

/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */
