/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */

if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "map")) {return new MapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "slotsMap")) {return new SlotsMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "slotsMapDeps")) {return new SlotsMapDepsLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "codeLikeSlotsMap")) {return new CodeLikeSlotsMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "assignmentMap")) {return new AssignmentMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "processMap")) {return new ProcessMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "mirrorMap")) {return new MirrorMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "blockMap")) {return new BlockMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "abstractVectorMap")) {return new AbstractVectorMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "byteVectorMap")) {return new ByteVectorMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "stringMap")) {return new StringMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "objVectorMap")) {return new ObjVectorMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "codeSlotsMap")) {return new CodeSlotsMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "methodMap")) {return new MethodMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "outerMethodMap")) {return new OuterMethodMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "blockMethodMap")) {return new BlockMethodMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "immediateMap")) {return new ImmediateMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "smiMap")) {return new SmiMapLayout();}
if (is_klein_string_equal_to_C_string(mapTypeSize, mapType, "floatMap")) {return new FloatMapLayout();}

/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */
