/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */

const BitCount mark_isByteVectorField_width = 1;
const BitCount mark_isByteVectorField_shift = 0;
const BitCount mark_compactMapIndexField_width = 4;
const BitCount mark_compactMapIndexField_shift = mark_isByteVectorField_width + mark_isByteVectorField_shift;
const int mark_compactMapIndexField_lowestEncodableNumber = 0;
const BitCount mark_objVectorIndexableOriginField_width = 2;
const BitCount mark_objVectorIndexableOriginField_shift = mark_compactMapIndexField_width + mark_compactMapIndexField_shift;
const int mark_objVectorIndexableOriginField_lowestEncodableNumber = 2;
const BitCount mark_objVectorIndexableSizeField_width = 4;
const BitCount mark_objVectorIndexableSizeField_shift = mark_objVectorIndexableOriginField_width + mark_objVectorIndexableOriginField_shift;
const int mark_objVectorIndexableSizeField_lowestEncodableNumber = 0;
const BitCount mark_hasBeenVisitedField_width = 1;
const BitCount mark_hasBeenVisitedField_shift = mark_objVectorIndexableSizeField_width + mark_objVectorIndexableSizeField_shift;
const BitCount mark_hashField_width = 18;
const BitCount mark_hashField_shift = mark_hasBeenVisitedField_width + mark_hasBeenVisitedField_shift;

/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */
