/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */

const BitCount slotType_slotTypeField_width = 2;
const BitCount slotType_slotTypeField_shift = 2;
const FieldValue slotType_slotTypeField_objectSlotValue = 0;
const FieldValue slotType_slotTypeField_mapSlotValue = 1;
const FieldValue slotType_slotTypeField_argumentSlotValue = 2;
const BitCount slotType_isParentField_width = 1;
const BitCount slotType_isParentField_shift = slotType_slotTypeField_width + slotType_slotTypeField_shift;
const BitCount slotType_isAssignableField_width = 1;
const BitCount slotType_isAssignableField_shift = slotType_isParentField_width + slotType_isParentField_shift;

/* THIS FILE WAS AUTO-GENERATED BY klein objectSystemSpitterOuter */
