# Sun-$Revision: 30.6 $

# Copyright 1999-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../../..
FILES        = Makefile
SELF_MODULES = 
DIRECTORIES = 

include        ${ROOT}/templates/sources.make
