# Sun-$Revision: 30.7 $

# Copyright 1999-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../../..
FILES        = Makefile
SELF_MODULES = javaUI2 \
	       javaCatReferrent \
	       javaUI2ACModel \
	       javaUI2ASModel \
	       javaUI2CUModel \
	       javaUI2CatModel \
	       javaUI2ClassModel \
	       javaUI2ImpDclModel \
	       javaUI2ImpPkgModel \
	       javaUI2InterfModel \
	       javaUI2PCModel \
	       javaUI2PkgModel \
	       javaUI2SlotModel \
	       javaUI2TDModel \

include        ${ROOT}/templates/sources.make
