# Sun-$Revision: 30.10 $

# Copyright 1994-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../../..
FILES        = Makefile
DIRECTORIES = 
SELF_MODULES =  \
  asmBitRange1 \
  asmBitRange2 \
  asmBitRange3 \
  asmFrame \
  asmFrame2 \
  asmFrame3 \
  asmFrame4 \
  asmFrame5 \
  asmFrameAbsGen \
  asmFrameGens \
  asmFrameRegs \
  asmFrameTemps1 \
  asmFrameTemps2 \

include        ${ROOT}/templates/sources.make
