# Sun-$Revision: 30.12 $

# Copyright 1999-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../..
FILES        = Makefile test.java
SELF_MODULES = \
        klein.self \
        kleinAbsPgmExporter.self \
        kleinAsmPgmExporter.self \
        kleinC1_Allocs.self \
        kleinC1_BCI.self \
        kleinC1_Gens.self \
        kleinC1_IRNodes.self \
        kleinC1_Values.self \
        kleinC1_locs.self \
        kleinCompiler.self \
        kleinCompiler0.self \
        kleinCompiler1.self \
        kleinCompiler2.self \
        kleinCompilerTester.self \
        kleinDB.self* \
        kleinExport.self \
        kleinExportList.self \
        kleinFrames.self \
        kleinJava.self* \
        kleinLenses.self \
        kleinMappedObjects.self \
        kleinMaps.self \
        kleinMemInterface.self \
        kleinMemory.self \
        kleinModels.self \
        kleinMorphs.self \
        kleinNMethod.self \
        kleinObjExporter.self \
        kleinObjMapper.self \
        kleinObjects.self \
        kleinOops.self \
        kleinPrims.self \
        kleinProxyClients.self \
        kleinProxySockets.self \
        kleinReflection.self \
        kleinRelocators.self \
        kleinResendDetector.self \
        kleinSelfVM.self \
        kleinSendDesc.self \
        kleinSlotType.self \
        kleinTestVM.self \
        kleinUI.self \
        kleinVM.self \
        kleinVMExporter.self \

DIRECTORIES = javaParser javaUI2
include        ${ROOT}/templates/sources.make
