# Sun-$Revision: 30.5 $

# Copyright 1994-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../../..
FILES        = Makefile
DIRECTORIES = 
SELF_MODULES =  \
  asmSPARC \
  asmSPARCBitRange \
  asmSPARCGens \


include        ${ROOT}/templates/sources.make
