# Sun-$Revision: 30.6 $

# Copyright 1994-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../../..
FILES        = Makefile
DIRECTORIES = 
SELF_MODULES =  \
  asmPPC \
  asmPPCBitRange \
  asmPPCGens \
  asmPPCReg1 \
  asmPPCReg2 \
  asmPPCReg3 \


include        ${ROOT}/templates/sources.make
