# Sun-$Revision: 30.7 $

# Copyright 1999-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../../..
FILES        = Makefile

SELF_MODULES = \
  allJavaParser \
  classNodeSum \
  classOrIntNodeSum \
  compUnitNodeSum \
  impOrPkgDclNodeSum \
  importDclNodeSum \
  intNodeSum \
  javaLexer \
  javaMinis \
  javaNodeSummaries \
  javaParseNodes \
  javaParser \
  javaParserTester \
  methOrConNodeSum \
  packageDclNodeSum \
  varDclNodeSum \

DIRECTORIES = tests

include        ${ROOT}/templates/sources.make
