# Sun-$Revision: 30.6 $

# Copyright 1994-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../..
FILES        = Makefile
DIRECTORIES = asmFrame asmPPC asmSPARC
SELF_MODULES =  asmKit

include        ${ROOT}/templates/sources.make
