# Sun-$Revision: 1.1.1.1 $
 
# Copyright 1994-2003 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile
DIRECTORIES  = unixDebugServer
include        ${ROOT}/templates/sources.make
